# -*- coding: utf-8 -*-
"""
正则表达式模式定义模块
用于内容清洗功能中的各种模式匹配
"""

import re

# 预编译常用的正则表达式模式
PATTERNS = {
    'ai_analysis': [
        re.compile(r'<tool_call>.*?</tool_call>[\s\r\n]*', re.DOTALL),
        re.compile(r'思考过程开始.*?思考过程结束[\s\r\n]*', re.DOTALL),
        re.compile(r'好的，.*?要求.*?。', re.DOTALL),
        re.compile(r'首先，.*?需求。', re.DOTALL),
        re.compile(r'接下来，.*?预期。', re.DOTALL),
        re.compile(r'然后，.*?一致。', re.DOTALL),
        re.compile(r'最后，.*?要求。', re.DOTALL),
        re.compile(r'总的来说，.*?要求。', re.DOTALL),
        re.compile(r'请补充内容：.*?$', re.DOTALL),
        re.compile(r'让我.*?扩写.*?内容。', re.DOTALL),
        re.compile(r'现在，我需要.*?扩写.*?内容。', re.DOTALL),
        re.compile(r'当前章节中，.*?然后.*?最后.*?。', re.DOTALL),
        re.compile(r'用户希望.*?扩展内容。', re.DOTALL),
        re.compile(r'在扩写过程中，.*?最后.*?。', re.DOTALL),
        re.compile(r'期待您的指示！'),
        re.compile(r'请您提供.*?版本。', re.DOTALL),
        re.compile(r'好，我现在需要帮用户扩写一个小说章节.*?如果需要调整或补充，请随时告诉我。', re.DOTALL),
        re.compile(r'如果您有其他想法，可以随时提出，我会进行调整。'),
        re.compile(r'希望这个扩展内容能满足你的要求。如果需要调整或补充，请随时告诉我。'),
        re.compile(r'希望这个扩展符合您的预期。如果需要更多细节或调整，请随时告诉我。'),
        re.compile(r'<tool_call>[\s\r\n]*', re.DOTALL),
        re.compile(r'首先，我需要考虑如何.*?。', re.DOTALL),
        re.compile(r'接下来，.*?可以更细致一些。', re.DOTALL),
        re.compile(r'对话部分也可以增加，.*?。', re.DOTALL),
        re.compile(r'在扩展过程中，我需要确保.*?。', re.DOTALL),
        re.compile(r'最后，结尾部分可以加入一些.*?。', re.DOTALL),
        re.compile(r'总的来说，我需要通过.*?。', re.DOTALL),
        re.compile(r'总的来说，.*?自然流畅。', re.DOTALL),
        re.compile(r'首先，我需要.*?。', re.DOTALL),
        re.compile(r'接下来，我需要.*?。', re.DOTALL),
        re.compile(r'最后，我需要.*?。', re.DOTALL),
        re.compile(r'让我.*?。', re.DOTALL),
        re.compile(r'首先，这.*?。', re.DOTALL),
        re.compile(r'然后，我需要.*?。', re.DOTALL),
        re.compile(r'好的，请您提供需要处理的文本，我会为您清理掉所有AI生成的分析内容，只保留小说正文。', re.DOTALL),
        re.compile(r'请提供需要处理的文本。'),
        re.compile(r'作为专业的小说编辑，你的任务是从以下文本中删除所有AI生成的分析内容，只保留小说正文。', re.DOTALL),
        re.compile(r'我的任务是识别并删除这些分析内容，只保留小说正文。', re.DOTALL),
        re.compile(r'接下来，我需要明确什么是AI生成的分析内容。', re.DOTALL),
        re.compile(r'通常，这包括对需求的分析、结构的理解、扩展重点等。', re.DOTALL),
        re.compile(r'而正文则是故事本身，包含情节、对话和人物描写等内容。', re.DOTALL),
        re.compile(r'我会逐段检查文本，判断每一部分是否属于分析内容还是正文。', re.DOTALL),
        re.compile(r'在确认哪些是需要保留的内容时，我会寻找明显的故事情节或人物互动部分。', re.DOTALL),
        re.compile(r'完成识别后，我将删除所有分析性内容，只保留小说正文，并确保格式不变，不添加任何额外信息。', re.DOTALL),
        re.compile(r'最后，我会输出清理后的正文，确保符合用户的要求，没有遗漏或错误。', re.DOTALL),
        re.compile(r'总结一下，我的步骤是：.*?。', re.DOTALL),
        re.compile(r'这样就能满足用户的需求，提供一个干净的小说正文。', re.DOTALL),
        re.compile(r'<tool_call>[\s\r\n]*', re.DOTALL),
        re.compile(r'</tool_call>[\s\r\n]*', re.DOTALL),
    ],
    'more_patterns': [
        re.compile(r'用户明确要求.*?。', re.DOTALL),
        re.compile(r'这意味着我需要.*?。', re.DOTALL),
        re.compile(r'首先，我会确定.*?。', re.DOTALL),
        re.compile(r'接下来，我要围绕主角.*?。', re.DOTALL),
        re.compile(r'关键是要有生动的场景和对话，让读者感受到紧张和悬念。', re.DOTALL),
        re.compile(r'好，我现在需要帮用户生成小说.*?。根据用户的请求，我得先仔细分析他的需求。', re.DOTALL),
        re.compile(r'首先，用户提供了一个详细的大纲，分为三个章节。', re.DOTALL),
        re.compile(r'最后，检查字数是否达到要求，并确保整体流畅，没有重复的内容。这样，扩写后的内容不仅丰富了故事，还深化了人物形象和主题。', re.DOTALL),
        re.compile(r'为了让内容更加自然连贯，我会先分析', re.DOTALL),
        re.compile(r'在写作时，我需要详细描写场景和对话，使情节生动有趣。', re.DOTALL),
    ],
    'writing_guide': [
        re.compile(r'在写作时，我需要详细描写场景和对话，使情节生动有趣。', re.DOTALL),
        re.compile(r'首先，我会.*?。然后.*?。接着.*?。最后.*?。', re.DOTALL),
        re.compile(r'在写作过程中，我要注意.*?。同时，加入一些.*?。', re.DOTALL),
        re.compile(r'通过这些思考，我可以.*?。', re.DOTALL),
        re.compile(r'当前章节.*?。', re.DOTALL),
        re.compile(r'同时，不要重复已有的内容。', re.DOTALL),
        re.compile(r'为了让内容更加丰富，我会先列出一些具体的扩展点：', re.DOTALL),
        re.compile(r'为了让故事更完整，我会先列出一些基本的情节安排。', re.DOTALL),
        re.compile(r'### 章节概要', re.DOTALL),
        re.compile(r'### 故事梗概', re.DOTALL),
        re.compile(r'### 世界观设定', re.DOTALL),
        re.compile(r'### 详细情节安排', re.DOTALL),
        re.compile(r'### 详细情节设计', re.DOTALL),
        re.compile(r'### 扩展问题框架', re.DOTALL),
        re.compile(r'### 补充内容概要', re.DOTALL),
        re.compile(r'### 详细扩展内容', re.DOTALL),
        re.compile(r'- \*\*.*?\*\*：.*?。', re.DOTALL),
        re.compile(r'- \*\*.*?\*\*：', re.DOTALL),
        re.compile(r'重点展现.*?。', re.DOTALL),
        re.compile(r'我们将重点描写.*?。', re.DOTALL),
        re.compile(r'这一段将重点描写.*?。', re.DOTALL),
        re.compile(r'这一段主要描写.*?。', re.DOTALL),
        re.compile(r'请您看看以下内容是否符合您的预期。', re.DOTALL),
        re.compile(r'希望这个故事.*?能满足你的要求。', re.DOTALL),
        re.compile(r'希望这个扩写能满足您的要求。', re.DOTALL),
        re.compile(r'希望这个扩展内容能满足你的要求。', re.DOTALL),
        re.compile(r'希望这个扩写内容能满足你的要求。', re.DOTALL),
        re.compile(r'希望这个故事片段能满足你的要求。', re.DOTALL),
        re.compile(r'希望这个故事开头能满足你的要求。', re.DOTALL),
        re.compile(r'希望这个扩展.*?。', re.DOTALL),
        re.compile(r'希望以上内容符合您的要求。', re.DOTALL),
        re.compile(r'---+', re.DOTALL),
    ],
    'extended_guide': [
        re.compile(r'\*\*写作提示\*\*：', re.DOTALL),
        re.compile(r'\*\*扩展内容：\*\*', re.DOTALL),
        re.compile(r'\*\*新增细节描写：\*\*', re.DOTALL),
        re.compile(r'\*\*增加对话内容：\*\*', re.DOTALL),
        re.compile(r'\*\*丰富内心独白：\*\*', re.DOTALL),
        re.compile(r'\*\*自然融入扩展：\*\*', re.DOTALL),
        re.compile(r'\*\*标题：.*?\*\*', re.DOTALL),
        re.compile(r'\*\*正文：\*\*', re.DOTALL),
        re.compile(r'\*\*尾声：\*\*', re.DOTALL),
        re.compile(r'\*\*扩展说明：\*\*', re.DOTALL),
        re.compile(r'【补充】', re.DOTALL),
        re.compile(r'【补充内容】', re.DOTALL),
    ],
    'chapter_analysis': [
        re.compile(r'为了让故事更加生动，我会先列出一些基本的问题来理清思路。', re.DOTALL),
        re.compile(r'为了让内容更加丰富完整，我会先列出一些补充的情节脉络。', re.DOTALL),
        re.compile(r'测试学院是挑选未来领导者的场所。', re.DOTALL),
        re.compile(r'在写作时，我需要详细描写场景和对话，使情节生动有趣。', re.DOTALL),
        re.compile(r'首先，我会.*?。然后.*?。接着.*?。最后.*?。', re.DOTALL),
        re.compile(r'在写作过程中，我要注意.*?。同时，加入一些.*?。', re.DOTALL),
        re.compile(r'通过这些思考，我可以.*?。', re.DOTALL),
        re.compile(r'\*\*接下来故事可能会沿着这些方向发展\*\*：', re.DOTALL),
        re.compile(r'\*\*结尾\*\*：', re.DOTALL),
        re.compile(r'当艾琳离开测试场时，天空依旧阴沉。她没有回头，也没有思考未来的方向。她知道，自己已经站在了一个新的起点上，而这场"最终测试"，才刚刚拉开序幕。', re.DOTALL),
        re.compile(r'希望以上内容符合您的要求。', re.DOTALL),
    ],
    'chapter_markers': [
        re.compile(r'\*\*标题：.*?\*\*', re.DOTALL),
        re.compile(r'\*\*正文：\*\*', re.DOTALL),
        re.compile(r'\*\*尾声：\*\*', re.DOTALL),
        re.compile(r'\*\*扩展内容：\*\*', re.DOTALL),
        re.compile(r'\*\*扩展说明：\*\*', re.DOTALL),
        re.compile(r'\*\*新增细节描写：\*\*', re.DOTALL),
        re.compile(r'\*\*增加对话内容：\*\*', re.DOTALL),
        re.compile(r'\*\*丰富内心独白：\*\*', re.DOTALL),
        re.compile(r'\*\*自然融入扩展：\*\*', re.DOTALL),
        re.compile(r'当前章节.*?。', re.DOTALL),
        re.compile(r'### 章节内容概要', re.DOTALL),
        re.compile(r'### 补充内容概要', re.DOTALL),
        re.compile(r'### 详细扩展内容', re.DOTALL),
        re.compile(r'接下来通过这些情节展现她的内心世界，并为后续发展埋下伏笔。', re.DOTALL),
        re.compile(r'同时，要确保扩展的内容与原故事主题一致，即艾琳在压力下的成长和选择。', re.DOTALL),
        re.compile(r'现在，我会逐步分析每个部分，寻找可以扩展的点，并添加必要的细节和对话，使章节更加丰满。', re.DOTALL),
        re.compile(r'为了让故事更丰富，我会先列出一些基本的情节发展脉络。', re.DOTALL),
        re.compile(r'艾琳是其中一个具有特殊天赋的学生，而伊恩教授掌握着重要的秘密实验。', re.DOTALL),
        re.compile(r'接下来', re.DOTALL),
    ]
}

def apply_patterns(text, pattern_group):
    """应用指定组的正则表达式模式"""
    for pattern in PATTERNS.get(pattern_group, []):
        text = pattern.sub('', text)
    return text

def apply_all_patterns(text):
    """应用所有预定义的正则表达式模式"""
    for group in PATTERNS:
        text = apply_patterns(text, group)
    return text